import streamlit as st
from rdkit import Chem
from rdkit.Chem import AllChem
import requests
import tempfile

# Function to fetch SMILES from molecule name
def get_smiles_from_name(name):
    try:
        url = f"https://cactus.nci.nih.gov/chemical/structure/{name}/smiles"
        response = requests.get(url)
        if response.status_code == 200:
            return response.text.strip()
        else:
            return None
    except Exception:
        return None

# Function to generate XYZ data from SMILES
def smiles_to_xyz(smiles):
    mol = Chem.MolFromSmiles(smiles)
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol, AllChem.ETKDG())
    AllChem.UFFOptimizeMolecule(mol)
    
    atoms = mol.GetAtoms()
    conf = mol.GetConformer()
    
    xyz_data = f"{len(atoms)}\nGenerated by RDKit\n"
    for atom in atoms:
        pos = conf.GetAtomPosition(atom.GetIdx())
        xyz_data += f"{atom.GetSymbol()} {pos.x:.4f} {pos.y:.4f} {pos.z:.4f}\n"
    return xyz_data

# Streamlit App UI
st.title("🔬 3D Molecule Viewer + .xyz Generator")

input_type = st.radio("Choose Input Type", ["Molecule Name", "SMILES"])
user_input = st.text_input("Enter Molecule Name or SMILES:")

if st.button("Generate .xyz File"):
    if not user_input.strip():
        st.error("Please enter a molecule name or SMILES.")
    else:
        if input_type == "Molecule Name":
            smiles = get_smiles_from_name(user_input)
            if not smiles:
                st.error("Could not find SMILES for the given molecule name.")
            else:
                st.success(f"Found SMILES: {smiles}")
        else:
            smiles = user_input

        if smiles:
            try:
                xyz_content = smiles_to_xyz(smiles)
                with tempfile.NamedTemporaryFile(delete=False, suffix=".xyz", mode="w") as f:
                    f.write(xyz_content)
                    temp_file_path = f.name

                with open(temp_file_path, "r") as f:
                    st.download_button("⬇️ Download .xyz File", f.read(), file_name="molecule.xyz")

                st.text("📄 XYZ File Content:")
                st.code(xyz_content, language="xyz")

            except Exception as e:
                st.error(f"Failed to generate .xyz file: {e}")
